# This is the default format. 
# For more see: https://github.com/mojombo/jekyll/wiki/Permalinks
permalink: /:categories/:title 

exclude: ["README.md", "package.json", "Gruntfile.js", "node_modules", "CNAME"]
highlighter: rouge
markdown: kramdown

# Themes are encouraged to use these universal variables 
# so be sure to set them if your theme uses them.
#
title : bjorsq
tagline: The personal site of Peter Edwards
author :
  name : Peter Edwards
  email : pete@bjorsq.net
  github : bjorsq

#sass
sass:
  sass_dir:           _scss
  style:              compressed

categories: ['blog', 'recipes']
asset_path: /assets/themes/bjorsq